return function()
	vim.g.alma3lol.bindings.nnoremap('<leader>bp', "<cmd>BufferLineTogglePin<CR>")
	vim.g.alma3lol.bindings.nnoremap('<leader>bg', "<cmd>TelescopeBufferLineToggleGroup<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader>1", "<cmd>BufferLineCyclePrev<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader>2", "<cmd>BufferLineCycleNext<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>1", "<CMD>BufferLineGoToBuffer 1<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>2", "<CMD>BufferLineGoToBuffer 2<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>3", "<CMD>BufferLineGoToBuffer 3<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>4", "<CMD>BufferLineGoToBuffer 4<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>5", "<CMD>BufferLineGoToBuffer 5<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>6", "<CMD>BufferLineGoToBuffer 6<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>7", "<CMD>BufferLineGoToBuffer 7<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>8", "<CMD>BufferLineGoToBuffer 8<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader><leader>9", "<CMD>BufferLineGoToBuffer 9<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader>bb", ":BufferLinePick<CR>")
end
