#!/bin/bash

battery() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	if [[ -z "$BAT" ]]; then
		echo "0"
	else
		cat /sys/class/power_supply/${BAT}/capacity
	fi
}
battery_stat() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	if [[ -z "$BAT" ]]; then
		echo "0"
	else
		cat /sys/class/power_supply/${BAT}/status
	fi
}

if [[ "$1" == "--bat" ]]; then
	battery
elif [[ "$1" == "--bat-st" ]]; then
	battery_stat
fi

