return function()
	vim.g.alma3lol.bindings.nnoremap("<leader>3", "#")
	vim.g.alma3lol.bindings.nnoremap("<leader>4", "$")
	vim.g.alma3lol.bindings.nnoremap("<leader>5", "%")
	vim.g.alma3lol.bindings.nnoremap("<leader>6", "^")
	vim.g.alma3lol.bindings.nnoremap("<leader>7", "&")
	vim.g.alma3lol.bindings.nnoremap("<leader>8", "*")
	vim.g.alma3lol.bindings.nnoremap("n", "nzzzv")
	vim.g.alma3lol.bindings.nnoremap("N", "Nzzzv")
	vim.g.alma3lol.bindings.nnoremap("<leader>k", ":m .-2<CR>==")
	vim.g.alma3lol.bindings.nnoremap("<leader>j", ":m .+1<CR>==")
	vim.g.alma3lol.bindings.vnoremap("<leader>j", ":m '>+1<CR>gv=gv")
	vim.g.alma3lol.bindings.vnoremap("<leader>k", ":m '<-2<CR>gv=gv")
	vim.g.alma3lol.bindings.inoremap("<c-j>", "<esc>:m .+1<CR>==a")
	vim.g.alma3lol.bindings.inoremap("<c-k>", "<esc>:m .-2<CR>==a")
end
