#!/bin/bash

if command -v node >/dev/null 2>&1; then
	PWD=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
	node "$PWD/aladhan.mjs"
else
	echo "You need to install NodeJS & fetch node modules"
fi
