#!/bin/bash

last_command_file="/tmp/eww_audio_ctrl_last_command"
echo $1 > $last_command_file

if [[ "$1" == "open" ]]; then
	eww open audio_ctl;
else
	sleep 1;
	last_command=`[[ -f $last_command_file ]] && cat $last_command_file`
	if [[ "$last_command" == "open" ]]; then
		exit
	fi
	eww close audio_ctl;
fi;
