#!/bin/bash

eww update weather_rev=false
eww update hig_rev=false

result=$(printf "Weather\nHIG" | rofi -dmenu -i -p "Choose a widget: ")

case $result in
	"Weather") eww update weather_rev=true ;;
	"HIG") eww update hig_rev=true ;;
esac
