#!/bin/bash

status=$(nmcli d | grep -E "wl*" | awk '{print $3}')
essid=$(nmcli c | grep -E "wl*" | awk -F'  ' '{print ($1)}')

if [[ $status == "disconnected" ]] ; then
    icon=""
    text=""
    col="#575268"

else
    icon=""
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi
