vim.g.alma3lol.bindings.nnoremap(',ll', '<cmd>Legendary<CR>')
vim.g.alma3lol.bindings.nnoremap(',lc', '<cmd>Legendary commands<CR>')
vim.g.alma3lol.bindings.nnoremap(',lk', '<cmd>Legendary keymaps<CR>')
vim.g.alma3lol.bindings.nnoremap(',la', '<cmd>Legendary autocmds<CR>')
vim.g.alma3lol.bindings.nnoremap(',lf', '<cmd>Legendary functions<CR>')
