#!/bin/bash

# Variables
CWD=`pwd`
ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/zsh"
RANGER="$HOME/.config/ranger"
ZELLIJ_CONFIG="$HOME/.config/zellij"
package_manager_command=''

# Checks
case `cat /etc/os-release | grep ID_LIKE | sed -e 's/ID_LIKE=//g'` in
	debian)
		package_manager_command='apt install -y'
		;;
	arch)
		package_manager_command='pacman -S --noconfirm'
		;;
esac

# Functions
mkdir_if_not_exists() {
	if [ ! -d $1 ]; then
		mkdir -p $1;
	fi
}
clone_if_not_exists() {
	if [ ! -d $2 ]; then
		git clone $1 $2
	fi
}
install_package_if_not_installed() {
	if !command -v $1 >/dev/null 2>&1; then
		`sudo $package_manager_command $1`;
	fi
}
download_if_not_exists() {
	if [ ! -f $2 ]; then
		curl -o $2 $1
	fi
}

# Required packages
echo """
[!] You need to install the following:
[+] Nerd Fonts Firacode
[+] Nerd Fonts JetBrainsMono
[+] Nerd Fonts Symbols
[+] Font Awesome
[+] Noto Emoji
[+] Noto color Emoji
"""

install_package_if_not_installed zsh
install_package_if_not_installed git
install_package_if_not_installed curl
install_package_if_not_installed jump
install_package_if_not_installed zoxide
install_package_if_not_installed starship
install_package_if_not_installed eww
install_package_if_not_installed acpi
install_package_if_not_installed terraform
install_package_if_not_installed bspwm
install_package_if_not_installed sxhkd
install_package_if_not_installed cava
install_package_if_not_installed ranger
install_package_if_not_installed exa
install_package_if_not_installed btop
install_package_if_not_installed fd
install_package_if_not_installed tealdeer
install_package_if_not_installed rofi
install_package_if_not_installed dunst
install_package_if_not_installed openrgb

# Dirs
mkdir_if_not_exists $ZSH_CUSTOM/plugins
mkdir_if_not_exists $RANGER/plugins
mkdir_if_not_exists $ZELLIJ_CONFIG/plugins

# ZSH plugins
curl -L https://git.io/antigen > $HOME/antigen.zsh

# Ranger plugins
clone_if_not_exists https://github.com/SL-RU/ranger_udisk_menu.git $RANGER/plugins/ranger_udisk_menu
clone_if_not_exists https://github.com/alexanderjeurissen/ranger_devicons.git $RANGER/plugins/ranger_devicons
clone_if_not_exists https://github.com/jchook/ranger-zoxide.git $RANGER/plugins/ranger-zoxide
clone_if_not_exists https://github.com/gsamokovarov/jump-ranger.git $RANGER/plugins/jump-ranger

if command -v vim >/dev/null 2>&1; then
	vim +PlugUpdate +PlugClean +PlugUpdate +qa
fi

if command -v nvim >/dev/null 2>&1; then
	nvim --headless '+lua vim.g.alma3lol.packer.ensure_packer()' '+lua vim.g.alma3lol.packer.setup()' '+PackerSync' +qa
fi

# BSPWM dual monitor
sudo echo "ACTION==\"change\", SUBSYSTEM==\"drm\", RUN+=\"/bin/su $USER --command='systemctl --user start bspwm-reload.service'\"" > /etc/udev/rules.d/99-reload-monitor.rules
