vim.g.alma3lol.bindings.nnoremap('<leader>gpto', '<cmd>ChatGPT<CR>')
vim.g.alma3lol.bindings.nnoremap('<leader>gpta', '<cmd>ChatGPTActAs<CR>')
vim.g.alma3lol.bindings.nnoremap('<leader>gpte', '<cmd>ChatGPTEditWithInstructions<CR>')
vim.g.alma3lol.bindings.xnoremap('<leader>gpte', '<cmd>ChatGPTEditWithInstructions<CR>')
vim.g.alma3lol.bindings.inoremap('<leader><leader>gpt', '<cmd>ChatGPTCompleteCode<CR>')
