vim.g.alma3lol.bindings.nnoremap('<leader>nsb', '<cmd>Telescope scratch<CR>')
vim.g.alma3lol.bindings.nnoremap('<leader>aa', '<cmd>Telescope telescope-alternate alternate_file<CR>')
vim.g.alma3lol.bindings.nnoremap('<leader>cff', "<cmd>Telescope find_files cwd=%:p:h<CR>")
vim.g.alma3lol.bindings.nnoremap('<leader>cfs', "<cmd>Telescope live_grep cwd=%:p:h<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>cfw", function()
	require('telescope.builtin').grep_string({ cwd = vim.fn.expand('%:p:h'), search = vim.fn.expand('<cword>') })
end)
vim.g.alma3lol.bindings.nnoremap(',fd', "<cmd>Telescope find_files cwd=$CWD<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>cd", '<cmd>Telescope file_browser hidden=true cwd=%:p:h<CR>')
vim.g.alma3lol.bindings.nnoremap("gr", "<cmd>Telescope lsp_references<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>ft", "<cmd>Telescope filetypes<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fw", function()
	require('telescope.builtin').grep_string({ search = vim.fn.expand('<cword>') })
end)
vim.g.alma3lol.bindings.nnoremap("<leader>fs", "<cmd>Telescope live_grep<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fh", "<cmd>Telescope help_tags<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fm", "<cmd>Telescope marks<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>ff", "<cmd>Telescope find_files hidden=true<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fd", "<cmd>Telescope file_browser hidden=true path=$CWD<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fe", "<cmd>Telescope file_browser hidden=true<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fb", "<cmd>Telescope buffers<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fr", "<cmd>Telescope frecency<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader><leader>w", "<cmd>Telescope workspaces<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>fws", "<cmd>Telescope lsp_workspace_symbols<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>cs", "<cmd>Telescope colorscheme<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader><leader>p", "<cmd>Telescope project<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>pp", "<cmd>Telescope command_palette<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>nc", "<cmd>Telescope neoclip<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>gf", "<cmd>Telescope git_files<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>vt", function()
	require('telescope.builtin').tags({
		ctags_file = vim.env.CTAGS_DIR .. vim.g.alma3lol.functions.UrlEncode(vim.fn.expand('%:p')) })
end)
vim.g.alma3lol.bindings.nnoremap("<leader>ts", "<cmd>TSPlaygroundToggle<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>tw", "<cmd>Telescope tmux windows<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>tp", "<cmd>Telescope tmux pane_contents<CR>")
vim.g.alma3lol.bindings.nnoremap(",fb", ":Telescope current_buffer_fuzzy_find<CR>")
vim.g.alma3lol.bindings.nnoremap(",sd", ":Telescope lsp_document_symbols<CR>")
vim.g.alma3lol.bindings.nnoremap(",sw", function()
	require('telescope.builtin').lsp_workspace_symbols({ query = vim.fn.expand("<cword>") })
end)
vim.g.alma3lol.bindings.nnoremap("<leader>mf", "<cmd>Telescope media_files<CR>")
