#!/bin/sh

alsactl init &
pulseaudio -k
pulseaudio --start
pgrep -x picom > /dev/null || picom -b --config $HOME/.config/picom/picom.jonaburg.conf &
# nitrogen --set-scaled ~/Pictures/WallPapers/ocean/ocean.png
# pgrep -x variety > /dev/null || variety &
feh --bg-fill $HOME/.config/eww/assets/wallpapers/powermenu.jpg
setxkbmap us,ar -option "grp:alt_shift_toggle" &
pgrep -x mpris-proxy > /dev/null || mpris-proxy &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x eww > /dev/null || eww daemon &
pgrep -x dunst > /dev/null || dunst &
# $HOME/.config/polybar/ocean/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
numlockx on &
xset -dpms &
xset s off &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio           0.52
bspc config border_width         2
bspc config window_gap          5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
for side in top right bottom left ; do
	bspc config ${side}_padding 5
done

bspc config normal_border_color         "#51576d"
bspc config active_border_color         "#9ece6a"
bspc config focused_border_color        "#9ece6a"
bspc config presel_feedback_color       "#d5a4b5"
bspc config urgent_border_color         "#d5a4b5"

bspc rule -a Screenkey manage=off
bspc rule -a kitty desktop='^1' follow=on
bspc rule -a Thunar desktop='^2' follow=on
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a Microsoft-edge desktop='^3' follow=on
bspc rule -a Slack desktop='^4' follow=on
bspc rule -a obs desktop='^5' follow=on
bspc rule -a TelegramDesktop desktop='^6' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Gimp-2.10 desktop='^8' follow=on
bspc rule -a Blender desktop='^8' follow=on
bspc rule -a kdenlive desktop='^8' follow=on
bspc rule -a Spotify desktop='^9' follow=on
bspc rule -a obsidian desktop='^10' follow=on
bspc rule -a Fig state=floating layer=above manage=off border=off
bspc rule -a "Fig:*:Fig Dashboard" manage=on border=on state=tiled
