vim.g.alma3lol.bindings.nnoremap('<leader>ccc', '<cmd>CodeCompanionChat<CR>')
vim.g.alma3lol.bindings.nnoremap('<leader>cca', '<cmd>CodeCompanionActions<CR>')
vim.g.alma3lol.bindings.nnoremap('<leader>ccm', '<cmd>CodeCompanion /commit<CR>')
vim.g.alma3lol.bindings.xnoremap('<leader>cce', '<cmd>CodeCompanion /explain<CR>')
vim.g.alma3lol.bindings.xnoremap('<leader>ccf', '<cmd>CodeCompanion /fix<CR>')
vim.g.alma3lol.bindings.xnoremap('<leader>cct', '<cmd>CodeCompanion /tests<CR>')
