vim.g.alma3lol.bindings.nnoremap("<leader>ca", ":Lspsaga code_action<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>hc", ":Lspsaga hover_doc<CR>")
vim.g.alma3lol.bindings.nnoremap("gd", ":Lspsaga goto_definition<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>gd", ":Lspsaga finder<CR>")
-- vim.g.alma3lol.bindings.nnoremap("<C-f>", "<cmd>lua require('lspsaga.hover').smart_scroll_hover(1)<CR>")
-- vim.g.alma3lol.bindings.nnoremap("<C-b>", "<cmd>lua require('lspsaga.hover').smart_scroll_hover(-1)<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>rn", ":Lspsaga rename<CR>")
vim.g.alma3lol.bindings.nnoremap("<leader>pd", ":Lspsaga peek_definition<CR>")
-- vim.g.alma3lol.bindings.nnoremap("<leader>sd", ":Lspsaga show_line_diagnostics<CR>")
vim.g.alma3lol.bindings.nnoremap("[d", ":Lspsaga diagnostic_jump_next<CR>")
vim.g.alma3lol.bindings.nnoremap("]d", ":Lspsaga diagnostic_jump_prev<CR>")
vim.g.alma3lol.bindings.vnoremap("<leader>ca", "<cmd><C-U>Lspsaga range_code_action<CR>")
