return function()
	vim.g.alma3lol.bindings.nnoremap("<leader>ca", ":Lspsaga code_action<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader>gs", ":Lspsaga signature_help<CR>")
	vim.g.alma3lol.bindings.nnoremap("gd", ":Lspsaga lsp_finder<CR>")
	vim.g.alma3lol.bindings.nnoremap("<C-f>", "<cmd>lua require('lspsaga.hover').smart_scroll_hover(1)<CR>")
	vim.g.alma3lol.bindings.nnoremap("<C-b>", "<cmd>lua require('lspsaga.hover').smart_scroll_hover(-1)<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader>rn", ":Lspsaga rename<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader>pd", ":Lspsaga preview_definition<CR>")
	vim.g.alma3lol.bindings.nnoremap("<leader>sd", ":Lspsaga show_line_diagnostics<CR>")
	vim.g.alma3lol.bindings.nnoremap("[d", ":Lspsaga diagnostic_jump_next<CR>")
	vim.g.alma3lol.bindings.nnoremap("]d", ":Lspsaga diagnostic_jump_prev<CR>")
	vim.g.alma3lol.bindings.nnoremap("<A-d>", ":Lspsaga open_floaterm<CR>")
	vim.g.alma3lol.bindings.vnoremap("<leader>ca", "<cmd><C-U>Lspsaga range_code_action<CR>")
	vim.g.alma3lol.bindings.tnoremap("<A-d> ", "<C-\\><C-n>:Lspsaga close_floaterm<CR>")
end
